Add metrics server run

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -130,6 +130,16 @@ then
 	exit 16
 fi
 
+mkdir --parents "${config_dir}/metrics"
+
+if ! cp "${buildpack_dir}/files/metrics/config.js" "${config_dir}/metrics/" \
+		2>/dev/null
+then
+	cmn::task::fail "Unable to copy configuration metrics"
+	cmn::step::fail
+	exit 16
+fi
+
 mkdir --parents "${build_dir}/bin"
 
 if ! cp "${buildpack_dir}/files/start" "${build_dir}/bin/start" \
